CREATE TYPE "CategoriaFiscalGasto" AS ENUM (
  'FINANCIACION_INTERESES',
  'CONSERVACION_REPARACION',
  'COMUNIDAD',
  'IBI_TASAS',
  'SEGUROS',
  'SUMINISTROS',
  'SERVICIOS_PROFESIONALES',
  'LIMPIEZA',
  'MOBILIARIO_ENSERES',
  'AMORTIZACION',
  'OTROS',
  'SIN_CLASIFICAR'
);

ALTER TABLE "Gasto"
  ADD COLUMN "categoria_fiscal" "CategoriaFiscalGasto" NOT NULL DEFAULT 'SIN_CLASIFICAR',
  ADD COLUMN "deducible_previsto" BOOLEAN,
  ADD COLUMN "notas_fiscales" TEXT,
  ADD COLUMN "prorrateo_fiscal" DOUBLE PRECISION;
