import { StyleSheet } from 'react-native';
import { Theme } from '@/constants/theme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Theme.colors.background },
  loader: { flex: 1 },
  content: {
    paddingHorizontal: Theme.spacing.lg,
    paddingTop: Theme.spacing.lg,
    paddingBottom: 96,
  },

  // — Empty state —
  emptyContainer: {
    alignItems: 'center',
    paddingTop: Theme.spacing.xxl,
    paddingHorizontal: Theme.spacing.xl,
    gap: Theme.spacing.md,
  },
  emptyIconBox: {
    width: 88,
    height: 88,
    borderRadius: Theme.radius.xl,
    backgroundColor: Theme.colors.primary + '15',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: Theme.spacing.sm,
  },
  emptyTitulo: {
    fontSize: Theme.typography.title,
    fontWeight: '800',
    color: Theme.colors.text,
    textAlign: 'center',
    letterSpacing: -0.3,
  },
  emptySubtitulo: {
    fontSize: Theme.typography.body,
    color: Theme.colors.textSecondary,
    textAlign: 'center',
    lineHeight: 24,
  },

  // — Tarjeta de anuncio (feed) —
  card: {
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.lg,
    marginBottom: Theme.spacing.base,
    shadowColor: Theme.colors.shadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.07,
    shadowRadius: 10,
    elevation: 3,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: Theme.spacing.sm,
  },
  cardTitulo: {
    flex: 1,
    fontSize: Theme.typography.subtitle,
    fontWeight: '700',
    color: Theme.colors.text,
    marginRight: Theme.spacing.sm,
    lineHeight: 24,
  },
  eliminarBtn: {
    width: 28,
    height: 28,
    borderRadius: Theme.radius.full,
    backgroundColor: Theme.colors.surface2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  eliminarBtnTexto: {
    fontSize: 12,
    color: Theme.colors.textTertiary,
    fontWeight: '700',
    lineHeight: 14,
  },
  cardContenido: {
    fontSize: Theme.typography.body,
    color: Theme.colors.textMedium,
    lineHeight: 24,
    marginBottom: Theme.spacing.base,
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: Theme.colors.border,
    paddingTop: Theme.spacing.sm,
  },
  cardAutorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  cardAutorDot: {
    width: 8,
    height: 8,
    borderRadius: Theme.radius.full,
    backgroundColor: Theme.colors.primary,
  },
  cardAutor: {
    fontSize: Theme.typography.label,
    color: Theme.colors.text,
    fontWeight: '700',
  },
  cardFecha: {
    fontSize: Theme.typography.caption,
    color: Theme.colors.textMuted,
  },

  // — FAB —
  fab: {
    position: 'absolute',
    bottom: Theme.spacing.lg,
    right: Theme.spacing.lg,
    width: 56,
    height: 56,
    borderRadius: Theme.radius.full,
    backgroundColor: Theme.colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: Theme.colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
  },
  fabTexto: {
    color: Theme.colors.surface,
    fontSize: Theme.typography.hero,
    lineHeight: 36,
    fontWeight: '300',
  },
  fabPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.95 }],
  },

  // — Modal (bottom sheet) —
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    backgroundColor: Theme.colors.surface,
    borderTopLeftRadius: Theme.radius.xl,
    borderTopRightRadius: Theme.radius.xl,
    padding: Theme.spacing.lg,
    paddingTop: Theme.spacing.xl,
    paddingBottom: 40,
    gap: Theme.spacing.md,
  },
  modalHandle: {
    width: 40,
    height: 4,
    borderRadius: Theme.radius.full,
    backgroundColor: Theme.colors.border,
    alignSelf: 'center',
    marginBottom: Theme.spacing.md,
  },
  modalTitulo: {
    fontSize: Theme.typography.title,
    fontWeight: '800',
    color: Theme.colors.text,
    letterSpacing: -0.3,
  },
  inputTitulo: {
    backgroundColor: Theme.colors.background,
    borderRadius: Theme.radius.md,
    borderWidth: 2,
    borderColor: Theme.colors.border,
    paddingHorizontal: Theme.spacing.base,
    paddingVertical: Theme.spacing.base,
    fontSize: Theme.typography.input,
    color: Theme.colors.text,
    minHeight: 52,
  },
  inputContenido: {
    backgroundColor: Theme.colors.background,
    borderRadius: Theme.radius.md,
    borderWidth: 2,
    borderColor: Theme.colors.border,
    paddingHorizontal: Theme.spacing.base,
    paddingVertical: Theme.spacing.base,
    fontSize: Theme.typography.body,
    color: Theme.colors.text,
    height: 130,
    lineHeight: 22,
  },
  modalAcciones: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
    marginTop: Theme.spacing.xs,
  },
  botonCancelar: {
    flex: 1,
    borderWidth: 2,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.lg,
    paddingVertical: 14,
    alignItems: 'center',
    minHeight: 52,
    justifyContent: 'center',
  },
  botonCancelarTexto: {
    color: Theme.colors.textMedium,
    fontSize: Theme.typography.body,
    fontWeight: '600',
  },
  botonPublicar: {
    flex: 1,
    backgroundColor: Theme.colors.primary,
    borderRadius: Theme.radius.lg,
    paddingVertical: 14,
    alignItems: 'center',
    minHeight: 52,
    justifyContent: 'center',
  },
  botonPublicarDisabled: {
    backgroundColor: Theme.colors.primaryDisabled,
  },
  botonPublicarTexto: {
    color: Theme.colors.surface,
    fontSize: Theme.typography.body,
    fontWeight: '700',
  },
  botonPressed: {
    opacity: 0.75,
    transform: [{ scale: 0.97 }],
  },
});
