import { StyleSheet } from 'react-native';
import { DefaultAppTheme, type AppTheme } from '@/constants/theme';

export const getPrimaryActionContentColor = (theme: AppTheme = DefaultAppTheme) =>
  theme.isDark ? theme.colors.backgroundDark : theme.colors.text;

export const createStyles = (theme: AppTheme = DefaultAppTheme) => StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background },
  loader: { flex: 1 },
  content: {
    paddingHorizontal: theme.spacing.lg,
    paddingTop: theme.spacing.lg,
    paddingBottom: 96,
  },

  emptyContainer: {
    alignItems: 'center',
    paddingTop: theme.spacing.xxl,
    paddingHorizontal: theme.spacing.xl,
    gap: theme.spacing.md,
  },
  emptyIconBox: {
    width: 88,
    height: 88,
    borderRadius: theme.radius.xl,
    backgroundColor: theme.colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: theme.spacing.sm,
  },
  emptyTitulo: {
    fontSize: theme.typography.title,
    fontWeight: '800',
    color: theme.colors.text,
    textAlign: 'center',
    letterSpacing: 0,
  },
  emptySubtitulo: {
    fontSize: theme.typography.body,
    color: theme.colors.textSecondary,
    textAlign: 'center',
    lineHeight: 24,
  },

  card: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    padding: theme.spacing.lg,
    marginBottom: theme.spacing.base,
    shadowColor: theme.colors.shadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: theme.isDark ? 0.18 : 0.07,
    shadowRadius: 10,
    elevation: 3,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: theme.spacing.sm,
  },
  cardTitulo: {
    flex: 1,
    fontSize: theme.typography.subtitle,
    fontWeight: '700',
    color: theme.colors.text,
    marginRight: theme.spacing.sm,
    lineHeight: 24,
  },
  eliminarBtn: {
    width: 28,
    height: 28,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.dangerLight,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: theme.colors.dangerText,
  },
  eliminarBtnTexto: {
    fontSize: 12,
    color: theme.colors.dangerText,
    fontWeight: '700',
    lineHeight: 14,
  },
  cardContenido: {
    fontSize: theme.typography.body,
    color: theme.colors.textMedium,
    lineHeight: 24,
    marginBottom: theme.spacing.base,
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: theme.colors.border,
    paddingTop: theme.spacing.sm,
  },
  cardAutorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  cardAutorDot: {
    width: 8,
    height: 8,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.primary,
  },
  cardAutor: {
    fontSize: theme.typography.label,
    color: theme.colors.text,
    fontWeight: '700',
  },
  cardFecha: {
    fontSize: theme.typography.caption,
    color: theme.colors.textMuted,
  },

  fab: {
    position: 'absolute',
    bottom: theme.spacing.lg,
    right: theme.spacing.lg,
    width: 56,
    height: 56,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: theme.isDark ? 0.24 : 0.28,
    shadowRadius: 8,
    elevation: 8,
  },
  fabTexto: {
    color: getPrimaryActionContentColor(theme),
    fontSize: theme.typography.hero,
    lineHeight: 36,
    fontWeight: '300',
  },
  fabPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.95 }],
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: theme.colors.overlay,
    justifyContent: 'flex-end',
  },
  modalBackdrop: {
    flex: 1,
  },
  modalContainer: {
    backgroundColor: theme.colors.surface,
    borderTopLeftRadius: theme.radius.xl,
    borderTopRightRadius: theme.radius.xl,
    padding: theme.spacing.lg,
    paddingTop: theme.spacing.xl,
    paddingBottom: 40,
    gap: theme.spacing.md,
    borderTopWidth: 1,
    borderColor: theme.colors.border,
  },
  modalHandle: {
    width: 40,
    height: 4,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.border,
    alignSelf: 'center',
    marginBottom: theme.spacing.md,
  },
  modalTitulo: {
    fontSize: theme.typography.title,
    fontWeight: '800',
    color: theme.colors.text,
    letterSpacing: 0,
  },
  inputTitulo: {
    backgroundColor: theme.colors.surface2,
    borderRadius: theme.radius.md,
    borderWidth: 2,
    borderColor: theme.colors.border,
    paddingHorizontal: theme.spacing.base,
    paddingVertical: theme.spacing.base,
    fontSize: theme.typography.input,
    color: theme.colors.text,
    minHeight: 52,
  },
  inputFocused: {
    borderColor: theme.colors.primary,
    backgroundColor: theme.colors.primaryLight,
  },
  inputContenido: {
    backgroundColor: theme.colors.surface2,
    borderRadius: theme.radius.md,
    borderWidth: 2,
    borderColor: theme.colors.border,
    paddingHorizontal: theme.spacing.base,
    paddingVertical: theme.spacing.base,
    fontSize: theme.typography.body,
    color: theme.colors.text,
    height: 130,
    lineHeight: 22,
  },
  modalAcciones: {
    flexDirection: 'row',
    gap: theme.spacing.md,
    marginTop: theme.spacing.xs,
  },
  botonCancelar: {
    flex: 1,
    borderWidth: 2,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.lg,
    paddingVertical: 14,
    alignItems: 'center',
    minHeight: 52,
    justifyContent: 'center',
  },
  botonCancelarTexto: {
    color: theme.colors.textMedium,
    fontSize: theme.typography.body,
    fontWeight: '600',
  },
  botonPublicar: {
    flex: 1,
    backgroundColor: theme.colors.primary,
    borderRadius: theme.radius.lg,
    paddingVertical: 14,
    alignItems: 'center',
    minHeight: 52,
    justifyContent: 'center',
  },
  botonPublicarDisabled: {
    backgroundColor: theme.colors.primaryDisabled,
  },
  botonPublicarTexto: {
    color: getPrimaryActionContentColor(theme),
    fontSize: theme.typography.body,
    fontWeight: '700',
  },
  botonPressed: {
    opacity: 0.75,
    transform: [{ scale: 0.97 }],
  },
});

export const styles = createStyles();
