import { StyleSheet } from 'react-native';
import { DefaultAppTheme, type AppTheme } from '@/constants/theme';

export const createStyles = (theme: AppTheme = DefaultAppTheme) => StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background },
  content: {
    paddingHorizontal: theme.spacing.lg,
    paddingTop: theme.spacing.lg,
    paddingBottom: 180,
  },

  header: {
    marginBottom: theme.spacing.lg,
  },
  headerEtiqueta: {
    fontSize: theme.typography.caption,
    fontWeight: '700',
    color: theme.colors.primary,
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    marginBottom: 4,
  },
  headerTitulo: {
    fontSize: 30,
    fontWeight: '800',
    color: theme.colors.text,
    letterSpacing: -0.5,
    lineHeight: 34,
  },
  headerSubtitulo: {
    fontSize: theme.typography.body,
    color: theme.colors.textSecondary,
    marginTop: 5,
    lineHeight: 22,
  },

  heroCard: {
    borderRadius: theme.radius.xl,
    padding: theme.spacing.xl,
    marginBottom: theme.spacing.xl,
    alignItems: 'stretch',
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
    ...theme.shadows.sm,
  },
  heroHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: theme.spacing.base,
    marginBottom: theme.spacing.lg,
  },
  heroIconBox: {
    width: 44,
    height: 44,
    borderRadius: theme.radius.lg,
    backgroundColor: theme.colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroHeaderTextos: {
    flex: 1,
    gap: theme.spacing.xs,
  },
  heroTitulo: {
    fontSize: theme.typography.subtitle,
    fontWeight: '800',
    color: theme.colors.text,
    letterSpacing: -0.2,
  },
  heroSubtitulo: {
    fontSize: theme.typography.label,
    color: theme.colors.textSecondary,
    lineHeight: 20,
  },
  heroImporte: {
    fontSize: theme.typography.hero,
    fontWeight: '900',
    letterSpacing: -1,
    lineHeight: 40,
  },
  heroResumenGrid: {
    flexDirection: 'row',
    gap: theme.spacing.md,
  },
  heroResumenCard: {
    flex: 1,
    borderRadius: theme.radius.lg,
    padding: theme.spacing.base,
    borderWidth: 1,
    borderColor: theme.colors.border,
    gap: theme.spacing.sm,
    ...theme.shadows.sm,
  },
  heroResumenBadge: {
    alignSelf: 'flex-start',
    borderRadius: theme.radius.full,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: 6,
  },
  heroResumenBadgeText: {
    fontSize: theme.typography.caption,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  heroResumenImporte: {
    fontSize: theme.typography.title,
    fontWeight: '900',
    letterSpacing: -0.4,
  },
  heroResumenTexto: {
    fontSize: theme.typography.label,
    color: theme.colors.textSecondary,
    lineHeight: 20,
  },
  caseroCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.xl,
    padding: theme.spacing.lg,
    marginBottom: theme.spacing.xl,
    borderWidth: 1,
    borderColor: theme.colors.border,
    gap: theme.spacing.base,
    ...theme.shadows.sm,
  },
  caseroHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: theme.spacing.base,
  },
  caseroIconBox: {
    width: 44,
    height: 44,
    borderRadius: theme.radius.lg,
    backgroundColor: theme.colors.infoLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  caseroHeaderTextos: {
    flex: 1,
    gap: theme.spacing.xs,
  },
  caseroTitulo: {
    fontSize: theme.typography.subtitle,
    fontWeight: '800',
    color: theme.colors.text,
    letterSpacing: -0.2,
  },
  caseroSubtitulo: {
    fontSize: theme.typography.label,
    color: theme.colors.textSecondary,
    lineHeight: 20,
  },
  caseroResumenGrid: {
    flexDirection: 'row',
    gap: theme.spacing.md,
  },
  caseroResumenCard: {
    flex: 1,
    borderRadius: theme.radius.lg,
    padding: theme.spacing.base,
    gap: theme.spacing.xs,
  },
  caseroResumenLabel: {
    fontSize: theme.typography.caption,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  caseroResumenImporte: {
    fontSize: theme.typography.subtitle,
    fontWeight: '900',
    letterSpacing: -0.3,
  },
  pendientesEmptyCard: {
    backgroundColor: theme.colors.successLight,
    borderRadius: theme.radius.lg,
    padding: theme.spacing.base,
    marginBottom: theme.spacing.xl,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: theme.spacing.base,
    borderWidth: 1,
    borderColor: theme.colors.success + '22',
  },
  pendientesEmptyIcon: {
    width: 44,
    height: 44,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pendientesEmptyTextos: {
    flex: 1,
    gap: theme.spacing.xs,
  },
  pendientesEmptyTitulo: {
    fontSize: theme.typography.body,
    fontWeight: '800',
    color: theme.colors.text,
  },
  pendientesEmptySubtitulo: {
    fontSize: theme.typography.label,
    color: theme.colors.textSecondary,
    lineHeight: 20,
  },
  errorCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: theme.spacing.base,
    backgroundColor: theme.colors.dangerLight,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    borderColor: theme.colors.danger + '28',
    padding: theme.spacing.base,
    marginBottom: theme.spacing.xl,
  },
  errorIconBox: {
    width: 44,
    height: 44,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  errorTextos: {
    flex: 1,
    gap: theme.spacing.xs,
  },
  errorTitulo: {
    fontSize: theme.typography.body,
    fontWeight: '800',
    color: theme.colors.text,
  },
  errorSubtitulo: {
    fontSize: theme.typography.label,
    color: theme.colors.textSecondary,
    lineHeight: 20,
  },

  seccionHeader: {
    marginBottom: theme.spacing.md,
    gap: theme.spacing.xs,
  },
  seccionHeaderCasero: {
    marginTop: theme.spacing.sm,
  },
  seccionTitulo: {
    fontSize: theme.typography.subtitle,
    fontWeight: '700',
    color: theme.colors.text,
  },
  seccionTituloSolo: {
    marginBottom: theme.spacing.md,
  },
  seccionSubtitulo: {
    fontSize: theme.typography.label,
    color: theme.colors.textSecondary,
    lineHeight: 20,
  },

  deudaCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    paddingVertical: theme.spacing.base,
    paddingHorizontal: theme.spacing.base,
    marginBottom: theme.spacing.md,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: theme.spacing.md,
    borderWidth: 1,
    borderColor: theme.colors.border,
    ...theme.shadows.sm,
  },
  deudaInfo: {
    flex: 1,
    gap: 4,
    justifyContent: 'center',
  },
  deudaNombre: {
    fontSize: theme.typography.body,
    fontWeight: '800',
    color: theme.colors.text,
    letterSpacing: -0.2,
  },
  deudaConcepto: {
    fontSize: theme.typography.caption,
    fontWeight: '500',
    color: theme.colors.textSecondary,
    lineHeight: 18,
  },
  deudaMeta: {
    minWidth: 110,
    alignItems: 'flex-end',
    justifyContent: 'center',
    gap: theme.spacing.sm,
  },
  deudaImporte: {
    fontSize: theme.typography.title,
    fontWeight: '900',
    letterSpacing: -0.4,
  },
  botonSaldar: {
    borderRadius: theme.radius.md,
    paddingVertical: 10,
    paddingHorizontal: theme.spacing.base,
    minWidth: 86,
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  botonSaldarPressed: {
    opacity: 0.82,
  },
  botonSaldarTexto: {
    fontSize: theme.typography.label,
    fontWeight: '800',
  },
  badgeEsperando: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: theme.radius.md,
    paddingVertical: 8,
    paddingHorizontal: 12,
    minHeight: 36,
  },
  badgeEsperandoTexto: {
    fontSize: theme.typography.caption,
    fontWeight: '800',
  },
  botonJustificante: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.xs,
    alignSelf: 'flex-start',
    backgroundColor: theme.colors.infoLight,
    borderRadius: theme.radius.full,
    paddingVertical: 10,
    paddingHorizontal: theme.spacing.base,
  },
  botonJustificanteTexto: {
    color: theme.colors.info,
    fontSize: theme.typography.label,
    fontWeight: '800',
  },
  botonFacturaOriginal: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: theme.spacing.xs,
    backgroundColor: theme.colors.primaryLight,
    borderRadius: theme.radius.full,
    paddingVertical: 10,
    paddingHorizontal: theme.spacing.base,
    marginTop: theme.spacing.xs,
  },
  botonFacturaOriginalTexto: {
    color: theme.colors.primary,
    fontSize: theme.typography.label,
    fontWeight: '800',
  },
  deudaPagadaCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    padding: theme.spacing.base,
    marginBottom: theme.spacing.sm,
    gap: theme.spacing.md,
    borderWidth: 1,
    borderColor: theme.colors.border,
    ...theme.shadows.sm,
  },
  deudaPagadaHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.md,
  },
  deudaPagadaInfo: {
    flex: 1,
    gap: 4,
  },
  deudaPagadaEstado: {
    alignSelf: 'flex-start',
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.successLight,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: 8,
  },
  deudaPagadaEstadoTexto: {
    color: theme.colors.success,
    fontSize: theme.typography.caption,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },

  gastoCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    padding: theme.spacing.base,
    marginBottom: theme.spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.md,
    shadowColor: theme.colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  gastoInfo: {
    flex: 1,
  },
  gastoConcepto: {
    fontSize: theme.typography.body,
    fontWeight: '700',
    color: theme.colors.text,
    letterSpacing: -0.2,
  },
  gastoPagador: {
    fontSize: theme.typography.caption,
    fontWeight: '600',
    color: theme.colors.textTertiary,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginTop: 3,
  },
  gastoFecha: {
    fontSize: theme.typography.caption,
    color: theme.colors.textMuted,
    marginTop: 2,
  },
  gastoImporteBox: {
    alignItems: 'flex-end',
  },
  gastoImporte: {
    fontSize: theme.typography.subtitle,
    fontWeight: '800',
    color: theme.colors.text,
    letterSpacing: -0.3,
  },
  gastoImporteSub: {
    fontSize: 11,
    fontWeight: '600',
    color: theme.colors.textTertiary,
    marginTop: 2,
  },

  emptyContainer: {
    alignItems: 'center',
    paddingVertical: theme.spacing.xxl,
    paddingHorizontal: theme.spacing.lg,
  },
  emptyIconBox: {
    width: 84,
    height: 84,
    borderRadius: theme.radius.xl,
    backgroundColor: theme.colors.primary + '15',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: theme.spacing.lg,
  },
  emptyTitulo: {
    fontSize: theme.typography.title,
    fontWeight: '800',
    color: theme.colors.text,
    textAlign: 'center',
    letterSpacing: -0.3,
    marginBottom: theme.spacing.sm,
  },
  emptySubtitulo: {
    fontSize: theme.typography.body,
    color: theme.colors.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: theme.colors.overlay,
    justifyContent: 'flex-end',
  },
  modalContainer: {
    backgroundColor: theme.colors.surface,
    borderTopLeftRadius: theme.radius.xl,
    borderTopRightRadius: theme.radius.xl,
    padding: theme.spacing.lg,
    paddingTop: theme.spacing.xl,
    paddingBottom: 40,
    gap: theme.spacing.md,
  },
  modalHandle: {
    width: 40,
    height: 4,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.border,
    alignSelf: 'center',
    marginBottom: theme.spacing.md,
  },
  modalTitulo: {
    fontSize: theme.typography.title,
    fontWeight: '800',
    color: theme.colors.text,
    letterSpacing: -0.3,
  },
  inputLabel: {
    fontSize: theme.typography.label,
    fontWeight: '700',
    color: theme.colors.textSecondary,
    marginBottom: theme.spacing.xs,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  input: {
    backgroundColor: theme.colors.background,
    borderRadius: theme.radius.md,
    borderWidth: 2,
    borderColor: theme.colors.border,
    paddingHorizontal: theme.spacing.base,
    paddingVertical: theme.spacing.base,
    fontSize: theme.typography.input,
    color: theme.colors.text,
    minHeight: 52,
  },
  participantesSection: {
    gap: theme.spacing.sm,
  },
  participantesRow: {
    gap: theme.spacing.sm,
    paddingRight: theme.spacing.sm,
  },
  participantePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.sm,
    paddingVertical: theme.spacing.sm,
    paddingHorizontal: theme.spacing.sm,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.background,
    borderWidth: 1.5,
    borderColor: theme.colors.border,
    minWidth: 124,
  },
  participantePillSelected: {
    backgroundColor: theme.colors.primary + '14',
    borderColor: theme.colors.primary + '38',
  },
  participantePillPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.97 }],
  },
  participanteTextoBox: {
    flex: 1,
    minWidth: 0,
  },
  participanteNombre: {
    fontSize: theme.typography.label,
    fontWeight: '700',
    color: theme.colors.text,
  },
  participanteNombreSelected: {
    color: theme.colors.primary,
  },
  participanteEstado: {
    fontSize: theme.typography.caption,
    fontWeight: '600',
    color: theme.colors.textMuted,
    marginTop: 2,
  },
  participanteEstadoSelected: {
    color: theme.colors.primary,
  },
  modalAcciones: {
    flexDirection: 'row',
    gap: theme.spacing.md,
    marginTop: theme.spacing.xs,
  },
  botonCancelar: {
    flex: 1,
    borderWidth: 2,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.lg,
    paddingVertical: 14,
    alignItems: 'center',
    minHeight: 52,
    justifyContent: 'center',
  },
  botonCancelarTexto: {
    color: theme.colors.textMedium,
    fontSize: theme.typography.body,
    fontWeight: '600',
  },
  botonGuardar: {
    flex: 1,
    backgroundColor: theme.colors.primary,
    borderRadius: theme.radius.lg,
    paddingVertical: 14,
    alignItems: 'center',
    minHeight: 52,
    justifyContent: 'center',
  },
  botonGuardarDisabled: {
    backgroundColor: theme.colors.primaryDisabled,
  },
  botonGuardarTexto: {
    color: theme.colors.surface,
    fontSize: theme.typography.body,
    fontWeight: '700',
  },
  botonPressed: {
    opacity: 0.75,
    transform: [{ scale: 0.97 }],
  },
  pagoSheet: {
    backgroundColor: theme.colors.surface,
    borderTopLeftRadius: theme.radius.xl,
    borderTopRightRadius: theme.radius.xl,
    paddingHorizontal: theme.spacing.lg,
    paddingTop: theme.spacing.xl,
    paddingBottom: theme.spacing.xl,
    gap: theme.spacing.base,
  },
  pagoSheetHero: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: theme.spacing.base,
    backgroundColor: theme.colors.surface2,
    borderRadius: theme.radius.lg,
    padding: theme.spacing.lg,
  },
  pagoSheetIcon: {
    width: 52,
    height: 52,
    borderRadius: theme.radius.lg,
    backgroundColor: theme.colors.successLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pagoSheetHeroTextos: {
    flex: 1,
    gap: theme.spacing.xs,
  },
  pagoSheetTitulo: {
    fontSize: theme.typography.title,
    fontWeight: '800',
    color: theme.colors.text,
    letterSpacing: -0.3,
  },
  pagoSheetSubtitulo: {
    fontSize: theme.typography.body,
    color: theme.colors.textSecondary,
    lineHeight: 22,
  },
  pagoSheetAmount: {
    fontSize: theme.typography.subtitle,
    fontWeight: '900',
    color: theme.colors.success,
  },
  pagoSheetOption: {
    borderRadius: theme.radius.lg,
    padding: theme.spacing.lg,
    gap: theme.spacing.sm,
    borderWidth: 1,
  },
  pagoSheetOptionSecundaria: {
    backgroundColor: theme.colors.surface2,
    borderColor: theme.colors.border,
  },
  pagoSheetOptionPrimaria: {
    backgroundColor: theme.colors.primaryLight,
    borderColor: theme.colors.primary + '24',
  },
  pagoSheetOptionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: theme.spacing.base,
  },
  pagoSheetOptionHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.sm,
    flex: 1,
  },
  pagoSheetOptionIcon: {
    width: 42,
    height: 42,
    borderRadius: theme.radius.full,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pagoSheetOptionIconSecundaria: {
    backgroundColor: theme.colors.surface,
  },
  pagoSheetOptionIconPrimaria: {
    backgroundColor: theme.colors.primary + '18',
  },
  pagoSheetOptionTitle: {
    fontSize: theme.typography.body,
    fontWeight: '800',
    color: theme.colors.text,
  },
  pagoSheetOptionDescription: {
    fontSize: theme.typography.label,
    color: theme.colors.textSecondary,
    lineHeight: 20,
  },
  pagoSheetFooter: {
    marginTop: theme.spacing.xs,
  },
  pagoSheetCancel: {
    borderRadius: theme.radius.lg,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.surface2,
  },
  pagoSheetCancelText: {
    color: theme.colors.textMedium,
    fontSize: theme.typography.body,
    fontWeight: '700',
  },

  fab: {
    position: 'absolute',
    bottom: 92,
    right: theme.spacing.lg,
    width: 58,
    height: 58,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 8,
  },
  fabPressed: {
    opacity: 0.85,
    transform: [{ scale: 0.95 }],
  },
});
