import { StyleSheet } from 'react-native';
import { Theme } from '@/constants/theme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Theme.colors.background },
  content: {
    paddingHorizontal: Theme.spacing.lg,
    paddingTop: Theme.spacing.lg,
    paddingBottom: 100,
  },

  header: {
    marginBottom: Theme.spacing.lg,
  },
  headerEtiqueta: {
    fontSize: Theme.typography.caption,
    fontWeight: '700',
    color: Theme.colors.primary,
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    marginBottom: 4,
  },
  headerTitulo: {
    fontSize: 30,
    fontWeight: '800',
    color: Theme.colors.text,
    letterSpacing: -0.5,
    lineHeight: 34,
  },
  headerSubtitulo: {
    fontSize: Theme.typography.body,
    color: Theme.colors.textSecondary,
    marginTop: 5,
    lineHeight: 22,
  },

  heroCard: {
    borderRadius: Theme.radius.xl,
    padding: Theme.spacing.xl,
    marginBottom: Theme.spacing.xl,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Theme.colors.border,
    ...Theme.shadows.sm,
  },
  heroEtiquetaBadge: {
    borderRadius: Theme.radius.full,
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: 7,
    marginBottom: Theme.spacing.md,
  },
  heroEtiqueta: {
    fontSize: Theme.typography.caption,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 1.4,
  },
  heroImporte: {
    fontSize: Theme.typography.hero,
    fontWeight: '900',
    letterSpacing: -1,
    lineHeight: 40,
  },
  heroDescripcion: {
    fontSize: Theme.typography.label,
    fontWeight: '600',
    marginTop: Theme.spacing.sm,
    color: Theme.colors.textSecondary,
    textAlign: 'center',
    lineHeight: 21,
  },

  seccionTitulo: {
    fontSize: Theme.typography.subtitle,
    fontWeight: '700',
    color: Theme.colors.text,
    marginBottom: Theme.spacing.md,
  },
  seccionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: Theme.spacing.base,
    marginTop: Theme.spacing.sm,
    marginBottom: Theme.spacing.md,
  },
  seccionHeaderTextos: {
    flex: 1,
  },
  seccionDescripcion: {
    fontSize: Theme.typography.label,
    color: Theme.colors.textSecondary,
    lineHeight: 20,
  },
  botonSecundario: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.xs,
    backgroundColor: Theme.colors.primaryLight,
    borderRadius: Theme.radius.full,
    paddingHorizontal: Theme.spacing.base,
    paddingVertical: 10,
    minHeight: 42,
  },
  botonSecundarioTexto: {
    color: Theme.colors.primary,
    fontSize: Theme.typography.label,
    fontWeight: '800',
  },

  deudaCard: {
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.lg,
    paddingVertical: Theme.spacing.base,
    paddingHorizontal: Theme.spacing.base,
    marginBottom: Theme.spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    ...Theme.shadows.sm,
  },
  deudaInfo: {
    flex: 1,
    gap: 4,
    justifyContent: 'center',
  },
  deudaNombre: {
    fontSize: Theme.typography.body,
    fontWeight: '800',
    color: Theme.colors.text,
    letterSpacing: -0.2,
  },
  deudaConcepto: {
    fontSize: Theme.typography.caption,
    fontWeight: '500',
    color: Theme.colors.textSecondary,
    lineHeight: 18,
  },
  deudaMeta: {
    minWidth: 110,
    alignItems: 'flex-end',
    justifyContent: 'center',
    gap: Theme.spacing.sm,
  },
  deudaImporte: {
    fontSize: Theme.typography.title,
    fontWeight: '900',
    letterSpacing: -0.4,
  },
  botonSaldar: {
    borderRadius: Theme.radius.md,
    paddingVertical: 10,
    paddingHorizontal: Theme.spacing.base,
    minWidth: 86,
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  botonSaldarPressed: {
    opacity: 0.82,
  },
  botonSaldarTexto: {
    fontSize: Theme.typography.label,
    fontWeight: '800',
  },
  badgeEsperando: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: Theme.radius.md,
    paddingVertical: 8,
    paddingHorizontal: 12,
    minHeight: 36,
  },
  badgeEsperandoTexto: {
    fontSize: Theme.typography.caption,
    fontWeight: '800',
  },
  botonJustificante: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.xs,
    alignSelf: 'flex-start',
    backgroundColor: Theme.colors.infoLight,
    borderRadius: Theme.radius.full,
    paddingVertical: 10,
    paddingHorizontal: Theme.spacing.base,
  },
  botonJustificanteTexto: {
    color: Theme.colors.info,
    fontSize: Theme.typography.label,
    fontWeight: '800',
  },
  deudaPagadaCard: {
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.base,
    marginBottom: Theme.spacing.sm,
    gap: Theme.spacing.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    ...Theme.shadows.sm,
  },
  deudaPagadaHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
  },
  deudaPagadaInfo: {
    flex: 1,
    gap: 4,
  },
  deudaPagadaEstado: {
    alignSelf: 'flex-start',
    borderRadius: Theme.radius.full,
    backgroundColor: Theme.colors.successLight,
    paddingHorizontal: Theme.spacing.sm,
    paddingVertical: 8,
  },
  deudaPagadaEstadoTexto: {
    color: Theme.colors.success,
    fontSize: Theme.typography.caption,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },

  mensualidadCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.base,
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.base,
    marginBottom: Theme.spacing.sm,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    ...Theme.shadows.sm,
  },
  mensualidadIcono: {
    width: 46,
    height: 46,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mensualidadInfo: {
    flex: 1,
    gap: 4,
  },
  mensualidadConcepto: {
    fontSize: Theme.typography.body,
    fontWeight: '800',
    color: Theme.colors.text,
  },
  mensualidadMeta: {
    fontSize: Theme.typography.label,
    color: Theme.colors.textSecondary,
  },
  mensualidadBadge: {
    borderRadius: Theme.radius.full,
    backgroundColor: Theme.colors.successLight,
    paddingHorizontal: Theme.spacing.sm,
    paddingVertical: 8,
  },
  mensualidadBadgeTexto: {
    color: Theme.colors.success,
    fontSize: Theme.typography.caption,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  mensualidadEmptyCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Theme.spacing.base,
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.base,
    marginBottom: Theme.spacing.xl,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  mensualidadEmptyIcon: {
    width: 40,
    height: 40,
    borderRadius: Theme.radius.full,
    backgroundColor: Theme.colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mensualidadEmptyTextos: {
    flex: 1,
    gap: 4,
  },
  mensualidadEmptyTitulo: {
    color: Theme.colors.text,
    fontSize: Theme.typography.body,
    fontWeight: '700',
  },
  mensualidadEmptySubtitulo: {
    color: Theme.colors.textSecondary,
    fontSize: Theme.typography.label,
    lineHeight: 20,
  },

  gastoCard: {
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.base,
    marginBottom: Theme.spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
    shadowColor: Theme.colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  gastoInfo: {
    flex: 1,
  },
  gastoConcepto: {
    fontSize: Theme.typography.body,
    fontWeight: '700',
    color: Theme.colors.text,
    letterSpacing: -0.2,
  },
  gastoPagador: {
    fontSize: Theme.typography.caption,
    fontWeight: '600',
    color: Theme.colors.textTertiary,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginTop: 3,
  },
  gastoFecha: {
    fontSize: Theme.typography.caption,
    color: Theme.colors.textMuted,
    marginTop: 2,
  },
  gastoImporteBox: {
    alignItems: 'flex-end',
  },
  gastoImporte: {
    fontSize: Theme.typography.subtitle,
    fontWeight: '800',
    color: Theme.colors.text,
    letterSpacing: -0.3,
  },
  gastoImporteSub: {
    fontSize: 11,
    fontWeight: '600',
    color: Theme.colors.textTertiary,
    marginTop: 2,
  },

  emptyContainer: {
    alignItems: 'center',
    paddingVertical: Theme.spacing.xxl,
    paddingHorizontal: Theme.spacing.lg,
  },
  emptyIconBox: {
    width: 84,
    height: 84,
    borderRadius: Theme.radius.xl,
    backgroundColor: Theme.colors.primary + '15',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: Theme.spacing.lg,
  },
  emptyTitulo: {
    fontSize: Theme.typography.title,
    fontWeight: '800',
    color: Theme.colors.text,
    textAlign: 'center',
    letterSpacing: -0.3,
    marginBottom: Theme.spacing.sm,
  },
  emptySubtitulo: {
    fontSize: Theme.typography.body,
    color: Theme.colors.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    backgroundColor: Theme.colors.surface,
    borderTopLeftRadius: Theme.radius.xl,
    borderTopRightRadius: Theme.radius.xl,
    padding: Theme.spacing.lg,
    paddingTop: Theme.spacing.xl,
    paddingBottom: 40,
    gap: Theme.spacing.md,
  },
  modalHandle: {
    width: 40,
    height: 4,
    borderRadius: Theme.radius.full,
    backgroundColor: Theme.colors.border,
    alignSelf: 'center',
    marginBottom: Theme.spacing.md,
  },
  modalTitulo: {
    fontSize: Theme.typography.title,
    fontWeight: '800',
    color: Theme.colors.text,
    letterSpacing: -0.3,
  },
  infoBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Theme.spacing.sm,
    backgroundColor: Theme.colors.primaryLight,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.base,
  },
  infoBannerTexto: {
    flex: 1,
    color: Theme.colors.primary,
    fontSize: Theme.typography.label,
    lineHeight: 20,
    fontWeight: '600',
  },
  inputLabel: {
    fontSize: Theme.typography.label,
    fontWeight: '700',
    color: Theme.colors.textSecondary,
    marginBottom: Theme.spacing.xs,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  input: {
    backgroundColor: Theme.colors.background,
    borderRadius: Theme.radius.md,
    borderWidth: 2,
    borderColor: Theme.colors.border,
    paddingHorizontal: Theme.spacing.base,
    paddingVertical: Theme.spacing.base,
    fontSize: Theme.typography.input,
    color: Theme.colors.text,
    minHeight: 52,
  },
  participantesSection: {
    gap: Theme.spacing.sm,
  },
  participantesRow: {
    gap: Theme.spacing.sm,
    paddingRight: Theme.spacing.sm,
  },
  participantePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
    paddingVertical: Theme.spacing.sm,
    paddingHorizontal: Theme.spacing.sm,
    borderRadius: Theme.radius.full,
    backgroundColor: Theme.colors.background,
    borderWidth: 1.5,
    borderColor: Theme.colors.border,
    minWidth: 124,
  },
  participantePillSelected: {
    backgroundColor: Theme.colors.primary + '14',
    borderColor: Theme.colors.primary + '38',
  },
  participantePillPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.97 }],
  },
  participanteTextoBox: {
    flex: 1,
    minWidth: 0,
  },
  participanteNombre: {
    fontSize: Theme.typography.label,
    fontWeight: '700',
    color: Theme.colors.text,
  },
  participanteNombreSelected: {
    color: Theme.colors.primary,
  },
  participanteEstado: {
    fontSize: Theme.typography.caption,
    fontWeight: '600',
    color: Theme.colors.textMuted,
    marginTop: 2,
  },
  participanteEstadoSelected: {
    color: Theme.colors.primary,
  },
  modalAcciones: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
    marginTop: Theme.spacing.xs,
  },
  botonCancelar: {
    flex: 1,
    borderWidth: 2,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.lg,
    paddingVertical: 14,
    alignItems: 'center',
    minHeight: 52,
    justifyContent: 'center',
  },
  botonCancelarTexto: {
    color: Theme.colors.textMedium,
    fontSize: Theme.typography.body,
    fontWeight: '600',
  },
  botonGuardar: {
    flex: 1,
    backgroundColor: Theme.colors.primary,
    borderRadius: Theme.radius.lg,
    paddingVertical: 14,
    alignItems: 'center',
    minHeight: 52,
    justifyContent: 'center',
  },
  botonGuardarDisabled: {
    backgroundColor: Theme.colors.primaryDisabled,
  },
  botonGuardarTexto: {
    color: Theme.colors.surface,
    fontSize: Theme.typography.body,
    fontWeight: '700',
  },
  botonPressed: {
    opacity: 0.75,
    transform: [{ scale: 0.97 }],
  },
  pagoSheet: {
    backgroundColor: Theme.colors.surface,
    borderTopLeftRadius: Theme.radius.xl,
    borderTopRightRadius: Theme.radius.xl,
    paddingHorizontal: Theme.spacing.lg,
    paddingTop: Theme.spacing.xl,
    paddingBottom: Theme.spacing.xl,
    gap: Theme.spacing.base,
  },
  pagoSheetHero: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Theme.spacing.base,
    backgroundColor: Theme.colors.surface2,
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.lg,
  },
  pagoSheetIcon: {
    width: 52,
    height: 52,
    borderRadius: Theme.radius.lg,
    backgroundColor: Theme.colors.successLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pagoSheetHeroTextos: {
    flex: 1,
    gap: Theme.spacing.xs,
  },
  pagoSheetTitulo: {
    fontSize: Theme.typography.title,
    fontWeight: '800',
    color: Theme.colors.text,
    letterSpacing: -0.3,
  },
  pagoSheetSubtitulo: {
    fontSize: Theme.typography.body,
    color: Theme.colors.textSecondary,
    lineHeight: 22,
  },
  pagoSheetAmount: {
    fontSize: Theme.typography.subtitle,
    fontWeight: '900',
    color: Theme.colors.success,
  },
  pagoSheetOption: {
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.lg,
    gap: Theme.spacing.sm,
    borderWidth: 1,
  },
  pagoSheetOptionSecundaria: {
    backgroundColor: Theme.colors.surface2,
    borderColor: Theme.colors.border,
  },
  pagoSheetOptionPrimaria: {
    backgroundColor: Theme.colors.primaryLight,
    borderColor: Theme.colors.primary + '24',
  },
  pagoSheetOptionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Theme.spacing.base,
  },
  pagoSheetOptionHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
    flex: 1,
  },
  pagoSheetOptionIcon: {
    width: 42,
    height: 42,
    borderRadius: Theme.radius.full,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pagoSheetOptionIconSecundaria: {
    backgroundColor: Theme.colors.surface,
  },
  pagoSheetOptionIconPrimaria: {
    backgroundColor: Theme.colors.primary + '18',
  },
  pagoSheetOptionTitle: {
    fontSize: Theme.typography.body,
    fontWeight: '800',
    color: Theme.colors.text,
  },
  pagoSheetOptionDescription: {
    fontSize: Theme.typography.label,
    color: Theme.colors.textSecondary,
    lineHeight: 20,
  },
  pagoSheetFooter: {
    marginTop: Theme.spacing.xs,
  },
  pagoSheetCancel: {
    borderRadius: Theme.radius.lg,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Theme.colors.surface2,
  },
  pagoSheetCancelText: {
    color: Theme.colors.textMedium,
    fontSize: Theme.typography.body,
    fontWeight: '700',
  },

  fab: {
    position: 'absolute',
    bottom: Theme.spacing.xl,
    right: Theme.spacing.lg,
    width: 58,
    height: 58,
    borderRadius: Theme.radius.full,
    backgroundColor: Theme.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Theme.colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 8,
  },
  fabPressed: {
    opacity: 0.85,
    transform: [{ scale: 0.95 }],
  },
});
