import { StyleSheet } from 'react-native';
import { AppTheme, DefaultAppTheme } from '@/constants/theme';

export const getEstadoBadgeColors = (theme: AppTheme = DefaultAppTheme) => ({
  bg: {
    PENDIENTE: `${theme.colors.warning}16`,
    PAGADA: `${theme.colors.success}18`,
  },
  text: {
    PENDIENTE: theme.colors.warning,
    PAGADA: theme.colors.success,
  },
  border: {
    PENDIENTE: `${theme.colors.warning}32`,
    PAGADA: `${theme.colors.success}30`,
  },
} as const);

export const createStyles = (theme: AppTheme = DefaultAppTheme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  content: {
    paddingHorizontal: theme.spacing.lg,
    paddingTop: theme.spacing.lg,
    paddingBottom: 120,
  },
  header: {
    marginBottom: theme.spacing.lg,
    gap: theme.spacing.sm,
  },
  headerEyebrow: {
    fontSize: theme.typography.caption,
    fontWeight: '800',
    color: theme.colors.textTertiary,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  headerTitle: {
    fontSize: theme.typography.hero,
    fontWeight: '800',
    color: theme.colors.text,
    letterSpacing: -0.8,
  },
  headerSubtitle: {
    fontSize: theme.typography.body,
    color: theme.colors.textSecondary,
    lineHeight: 22,
  },
  viviendaSelector: {
    marginBottom: theme.spacing.lg,
  },
  viviendaSelectorContent: {
    gap: theme.spacing.sm,
    paddingRight: theme.spacing.sm,
  },
  viviendaChip: {
    paddingHorizontal: theme.spacing.base,
    paddingVertical: theme.spacing.sm,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.surface,
    borderWidth: 1.5,
    borderColor: theme.colors.border,
  },
  viviendaChipActive: {
    backgroundColor: theme.colors.primaryLight,
    borderColor: theme.colors.primary,
  },
  viviendaChipText: {
    fontSize: theme.typography.label,
    fontWeight: '700',
    color: theme.colors.textSecondary,
  },
  viviendaChipTextActive: {
    color: theme.colors.primary,
  },
  heroCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.xl,
    padding: theme.spacing.lg,
    marginBottom: theme.spacing.xl,
    gap: theme.spacing.lg,
    ...theme.shadows.sm,
  },
  invoiceButton: {
    marginBottom: theme.spacing.xl,
  },
  heroTop: {
    gap: theme.spacing.xs,
  },
  heroLabel: {
    fontSize: theme.typography.caption,
    fontWeight: '800',
    color: theme.colors.textTertiary,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  heroTitle: {
    fontSize: theme.typography.heading,
    fontWeight: '800',
    color: theme.colors.text,
    letterSpacing: -0.4,
  },
  heroAddress: {
    fontSize: theme.typography.label,
    color: theme.colors.textSecondary,
    lineHeight: 20,
  },
  heroAmounts: {
    flexDirection: 'row',
    gap: theme.spacing.base,
  },
  heroAmountCard: {
    flex: 1,
    borderRadius: theme.radius.lg,
    padding: theme.spacing.base,
    gap: theme.spacing.xs,
  },
  heroAmountCardPaid: {
    backgroundColor: `${theme.colors.success}12`,
  },
  heroAmountCardPending: {
    backgroundColor: `${theme.colors.warning}14`,
  },
  heroAmountLabel: {
    fontSize: theme.typography.caption,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  heroAmountLabelPaid: {
    color: theme.colors.success,
  },
  heroAmountLabelPending: {
    color: theme.colors.warning,
  },
  heroAmountValue: {
    fontSize: theme.typography.heading,
    fontWeight: '800',
    color: theme.colors.text,
    letterSpacing: -0.5,
  },
  heroAmountHelp: {
    fontSize: theme.typography.caption,
    color: theme.colors.textSecondary,
    lineHeight: 18,
  },
  section: {
    marginBottom: theme.spacing.xl,
  },
  sectionHeader: {
    marginBottom: theme.spacing.base,
    gap: theme.spacing.xs,
  },
  sectionTitle: {
    fontSize: theme.typography.subtitle,
    fontWeight: '800',
    color: theme.colors.text,
  },
  sectionSubtitle: {
    fontSize: theme.typography.label,
    color: theme.colors.textSecondary,
  },
  debtList: {
    gap: theme.spacing.base,
  },
  invoiceList: {
    gap: theme.spacing.base,
  },
  currentInvoiceList: {
    gap: theme.spacing.base,
  },
  invoiceCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    padding: theme.spacing.base,
    gap: theme.spacing.base,
    ...theme.shadows.sm,
  },
  invoiceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.base,
  },
  invoiceIcon: {
    width: 48,
    height: 48,
    borderRadius: theme.radius.lg,
    backgroundColor: theme.colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  invoiceBody: {
    flex: 1,
    gap: theme.spacing.xs,
  },
  invoiceConcept: {
    fontSize: theme.typography.body,
    fontWeight: '800',
    color: theme.colors.text,
    lineHeight: 21,
  },
  invoiceMeta: {
    fontSize: theme.typography.caption,
    color: theme.colors.textTertiary,
  },
  invoiceEditButton: {
    borderRadius: theme.radius.lg,
    backgroundColor: theme.colors.primaryLight,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.xs,
    flexShrink: 0,
  },
  invoiceEditButtonDisabled: {
    backgroundColor: theme.colors.surface2,
  },
  invoiceEditText: {
    fontSize: theme.typography.caption,
    fontWeight: '800',
    color: theme.colors.primary,
  },
  invoiceEditTextDisabled: {
    color: theme.colors.textMuted,
  },
  invoiceFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: theme.spacing.base,
    paddingTop: theme.spacing.base,
    borderTopWidth: 1,
    borderTopColor: theme.colors.border,
  },
  invoiceAmount: {
    fontSize: theme.typography.heading,
    fontWeight: '800',
    color: theme.colors.text,
  },
  invoiceStatus: {
    fontSize: theme.typography.caption,
    fontWeight: '800',
    color: theme.colors.textSecondary,
    textAlign: 'right',
    flexShrink: 1,
  },
  invoiceTrace: {
    fontSize: theme.typography.caption,
    fontWeight: '700',
    color: theme.colors.textTertiary,
    lineHeight: 18,
  },
  debtCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    padding: theme.spacing.base,
    ...theme.shadows.sm,
  },
  debtRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.base,
  },
  avatar: {
    width: 56,
    height: 56,
    borderRadius: theme.radius.full,
    backgroundColor: `${theme.colors.primary}14`,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  avatarText: {
    fontSize: theme.typography.subtitle,
    fontWeight: '800',
    color: theme.colors.primary,
  },
  debtBody: {
    flex: 1,
    gap: theme.spacing.xs,
  },
  debtName: {
    fontSize: theme.typography.body,
    fontWeight: '800',
    color: theme.colors.text,
  },
  debtConcept: {
    fontSize: theme.typography.label,
    color: theme.colors.textSecondary,
    lineHeight: 20,
  },
  debtDate: {
    fontSize: theme.typography.caption,
    color: theme.colors.textTertiary,
  },
  debtMeta: {
    alignItems: 'flex-end',
    gap: theme.spacing.sm,
  },
  debtAmount: {
    fontSize: theme.typography.subtitle,
    fontWeight: '800',
    color: theme.colors.text,
  },
  statusBadge: {
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
    borderRadius: theme.radius.full,
    borderWidth: 1,
  },
  statusBadgeText: {
    fontSize: theme.typography.caption,
    fontWeight: '800',
  },
  receiptLink: {
    marginTop: theme.spacing.base,
    alignSelf: 'flex-start',
    backgroundColor: `${theme.colors.info}12`,
    borderRadius: theme.radius.full,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.xs,
  },
  receiptLinkText: {
    fontSize: theme.typography.caption,
    fontWeight: '800',
    color: theme.colors.info,
  },
  invoiceLink: {
    marginTop: theme.spacing.sm,
    alignSelf: 'flex-start',
    backgroundColor: theme.colors.primaryLight,
    borderRadius: theme.radius.full,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.xs,
  },
  invoiceLinkText: {
    fontSize: theme.typography.caption,
    fontWeight: '800',
    color: theme.colors.primary,
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: theme.spacing.xxl,
    paddingHorizontal: theme.spacing.xl,
  },
  emptyIconBox: {
    width: 92,
    height: 92,
    borderRadius: theme.radius.xl,
    backgroundColor: `${theme.colors.primary}12`,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: theme.spacing.lg,
  },
  emptyTitle: {
    fontSize: theme.typography.heading,
    fontWeight: '800',
    color: theme.colors.text,
    textAlign: 'center',
  },
  emptySubtitle: {
    marginTop: theme.spacing.sm,
    fontSize: theme.typography.body,
    color: theme.colors.textSecondary,
    textAlign: 'center',
    lineHeight: 24,
  },
  emptyAction: {
    width: '100%',
    marginTop: theme.spacing.xl,
  },
  errorCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: theme.spacing.base,
    backgroundColor: theme.colors.dangerLight,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    borderColor: `${theme.colors.danger}28`,
    padding: theme.spacing.base,
    marginBottom: theme.spacing.xl,
  },
  errorIcon: {
    width: 44,
    height: 44,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  errorTextBox: {
    flex: 1,
    gap: theme.spacing.xs,
  },
  errorTitle: {
    fontSize: theme.typography.body,
    fontWeight: '800',
    color: theme.colors.text,
  },
  errorText: {
    fontSize: theme.typography.label,
    color: theme.colors.textSecondary,
    lineHeight: 20,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: theme.colors.overlay,
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: theme.colors.background,
    borderTopLeftRadius: theme.radius.xl,
    borderTopRightRadius: theme.radius.xl,
    paddingHorizontal: theme.spacing.lg,
    paddingTop: theme.spacing.md,
    paddingBottom: theme.spacing.xl,
  },
  invoiceSheet: {
    maxHeight: '92%',
    backgroundColor: theme.colors.surface,
    borderTopLeftRadius: theme.radius.lg,
    borderTopRightRadius: theme.radius.lg,
    paddingHorizontal: theme.spacing.lg,
    paddingTop: theme.spacing.md,
    paddingBottom: theme.spacing.xl,
  },
  invoiceContent: {
    gap: theme.spacing.base,
    paddingBottom: theme.spacing.lg,
  },
  formGroup: {
    gap: theme.spacing.xs,
  },
  formRow: {
    flexDirection: 'row',
    gap: theme.spacing.md,
  },
  formRowItem: {
    flex: 1,
    gap: theme.spacing.xs,
  },
  inputLabel: {
    fontSize: theme.typography.caption,
    fontWeight: '800',
    color: theme.colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  textInput: {
    minHeight: 52,
    borderRadius: theme.radius.lg,
    borderWidth: 1.5,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.background,
    paddingHorizontal: theme.spacing.base,
    fontSize: theme.typography.input,
    color: theme.colors.text,
  },
  attachmentButton: {
    minHeight: 68,
    borderRadius: theme.radius.lg,
    backgroundColor: theme.colors.infoLight,
    padding: theme.spacing.base,
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.base,
  },
  attachmentIcon: {
    width: 44,
    height: 44,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  attachmentTextBox: {
    flex: 1,
    minWidth: 0,
    gap: theme.spacing.xs,
  },
  attachmentTitle: {
    fontSize: theme.typography.body,
    fontWeight: '800',
    color: theme.colors.text,
  },
  attachmentSubtitle: {
    fontSize: theme.typography.caption,
    color: theme.colors.textSecondary,
  },
  splitHeader: {
    gap: theme.spacing.xs,
  },
  tenantList: {
    gap: theme.spacing.sm,
  },
  tenantRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.base,
    borderRadius: theme.radius.lg,
    backgroundColor: theme.colors.background,
    padding: theme.spacing.sm,
    minHeight: 76,
  },
  tenantRowDisabled: {
    opacity: 0.62,
  },
  participantToggle: {
    width: 32,
    height: 32,
    borderRadius: theme.radius.full,
    borderWidth: 1.5,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  participantToggleActive: {
    borderColor: theme.colors.primary,
    backgroundColor: theme.colors.primary,
  },
  tenantInfo: {
    flex: 1,
    minWidth: 0,
    gap: theme.spacing.xs,
  },
  splitInput: {
    width: 96,
    minHeight: 48,
    borderRadius: theme.radius.lg,
    borderWidth: 1.5,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.surface,
    paddingHorizontal: theme.spacing.md,
    textAlign: 'right',
    fontSize: theme.typography.input,
    fontWeight: '800',
    color: theme.colors.text,
  },
  splitInputDisabled: {
    backgroundColor: theme.colors.surface2,
    color: theme.colors.textMuted,
  },
  totalCounter: {
    borderRadius: theme.radius.lg,
    backgroundColor: `${theme.colors.warning}14`,
    padding: theme.spacing.base,
    borderWidth: 1,
    borderColor: `${theme.colors.warning}32`,
  },
  totalCounterOk: {
    backgroundColor: theme.colors.successLight,
    borderColor: `${theme.colors.success}30`,
  },
  totalCounterText: {
    fontSize: theme.typography.label,
    fontWeight: '800',
    color: theme.colors.warning,
    textAlign: 'center',
  },
  totalCounterTextOk: {
    color: theme.colors.success,
  },
  totalCounterHelp: {
    marginTop: theme.spacing.xs,
    fontSize: theme.typography.caption,
    fontWeight: '700',
    color: theme.colors.textSecondary,
    textAlign: 'center',
    lineHeight: 18,
  },
  totalCounterHelpOk: {
    color: theme.colors.success,
  },
  modalHandle: {
    width: 44,
    height: 4,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.textMuted,
    alignSelf: 'center',
    marginBottom: theme.spacing.base,
  },
  modalTitle: {
    fontSize: theme.typography.heading,
    fontWeight: '800',
    color: theme.colors.text,
    marginBottom: theme.spacing.xs,
  },
  modalSubtitle: {
    fontSize: theme.typography.label,
    color: theme.colors.textSecondary,
    lineHeight: 20,
    marginBottom: theme.spacing.lg,
  },
  modalImageWrap: {
    width: '100%',
    height: 320,
    borderRadius: theme.radius.xl,
    overflow: 'hidden',
    backgroundColor: theme.colors.surface2,
    marginBottom: theme.spacing.lg,
  },
  modalImage: {
    width: '100%',
    height: '100%',
    backgroundColor: theme.colors.surface2,
  },
  modalActions: {
    flexDirection: 'row',
    gap: theme.spacing.sm,
  },
  modalAction: {
    flex: 1,
  },
  editForm: {
    gap: theme.spacing.base,
    marginBottom: theme.spacing.lg,
  },
  invoicePhotoBlock: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    borderColor: theme.colors.border,
    padding: theme.spacing.base,
    gap: theme.spacing.base,
    marginBottom: theme.spacing.lg,
  },
  invoicePhotoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.md,
  },
  invoicePhotoIcon: {
    width: 40,
    height: 40,
    borderRadius: theme.radius.lg,
    backgroundColor: theme.colors.infoLight,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  invoicePhotoCopy: {
    flex: 1,
    gap: theme.spacing.xs,
  },
  invoicePhotoTitle: {
    fontSize: theme.typography.label,
    fontWeight: '800',
    color: theme.colors.text,
  },
  invoicePhotoSubtitle: {
    fontSize: theme.typography.caption,
    color: theme.colors.textSecondary,
    lineHeight: 18,
  },
  invoicePhotoPreview: {
    height: 150,
    borderRadius: theme.radius.lg,
    overflow: 'hidden',
    backgroundColor: theme.colors.surface2,
  },
  invoicePhotoImage: {
    width: '100%',
    height: '100%',
  },
  warningBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: theme.spacing.sm,
    backgroundColor: theme.colors.warningLight,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    borderColor: `${theme.colors.warning}30`,
    padding: theme.spacing.base,
    marginBottom: theme.spacing.lg,
  },
  warningBannerText: {
    flex: 1,
    fontSize: theme.typography.label,
    color: theme.colors.textMedium,
    lineHeight: 20,
    fontWeight: '600',
  },
});

export const styles = createStyles();
