import { StyleSheet } from 'react-native';
import { Theme } from '@/constants/theme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Theme.colors.background },
  list: { padding: Theme.spacing.base },
  cardTitle: { fontSize: 18, fontWeight: '700', marginBottom: Theme.spacing.xs },
  cardAddress: { fontSize: 14, color: Theme.colors.textSecondary, marginBottom: Theme.spacing.sm },
  cardRooms: { fontSize: Theme.typography.label, color: Theme.colors.primary, fontWeight: '600' },
  loaderContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  emptyText: { textAlign: 'center', marginTop: 40, color: Theme.colors.textTertiary, fontSize: Theme.typography.input },
  emptySubtext: { textAlign: 'center', marginTop: Theme.spacing.sm, color: Theme.colors.textMuted, fontSize: 14 },
  fab: {
    position: 'absolute',
    bottom: Theme.spacing.lg,
    right: Theme.spacing.lg,
    width: 56,
    height: 56,
    borderRadius: Theme.radius.full,
    backgroundColor: Theme.colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: Theme.colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 8,
  },
  fabText: { color: Theme.colors.surface, fontSize: Theme.typography.hero, lineHeight: 36, fontWeight: '300' },
  iconoPerfil: {
    position: 'absolute',
    top: Theme.spacing.base,
    right: Theme.spacing.base,
    zIndex: 10,
  },
  badge: {
    position: 'absolute',
    top: 10,
    right: 10,
    minWidth: 22,
    height: 22,
    borderRadius: 11,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 5,
    zIndex: 1,
  },
  badgeVerde: { backgroundColor: Theme.colors.success },
  badgeAmarillo: { backgroundColor: Theme.colors.warning },
  badgeRojo: { backgroundColor: Theme.colors.danger },
  badgeTexto: {
    color: Theme.colors.surface,
    fontSize: 11,
    fontWeight: '700',
  },
});
