import { StyleSheet } from 'react-native';
import { DefaultAppTheme, type AppTheme } from '@/constants/theme';

export const createStyles = (theme: AppTheme = DefaultAppTheme) => StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background },
  content: { padding: theme.spacing.base, paddingBottom: 48 },
  errorTexto: { textAlign: 'center', marginTop: 40, color: theme.colors.textTertiary },
  enlacePressed: { opacity: 0.6 },

  // — Header card —
  headerCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    padding: theme.spacing.lg,
    marginBottom: theme.spacing.base,
    shadowColor: theme.colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  headerNombre: {
    fontSize: 24,
    fontWeight: '800',
    color: theme.colors.text,
    letterSpacing: 0,
    marginBottom: 4,
  },
  headerDireccion: {
    fontSize: theme.typography.body,
    color: theme.colors.textSecondary,
    fontWeight: '500',
    marginBottom: theme.spacing.md,
  },
  headerChips: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  chipHabitaciones: {
    backgroundColor: theme.colors.infoLight,
    borderRadius: theme.radius.full,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  chipHabitacionesTexto: {
    fontSize: 12,
    fontWeight: '700',
    color: theme.colors.info,
  },
  chipInquilinos: {
    backgroundColor: theme.colors.successLight,
    borderRadius: theme.radius.full,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  chipInquilinosTexto: {
    fontSize: 12,
    fontWeight: '700',
    color: theme.colors.success,
  },

  // — Accesos rápidos —
  accionesGrid: {
    flexDirection: 'row',
    gap: theme.spacing.md,
    marginBottom: theme.spacing.base,
  },
  accionBtn: {
    flex: 1,
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    padding: theme.spacing.lg,
    alignItems: 'center',
    shadowColor: theme.colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
    gap: 10,
  },
  accionBtnPressed: { opacity: 0.75 },
  accionIconIncidencias: {
    backgroundColor: theme.colors.warningLight,
    borderRadius: theme.radius.md,
    padding: 12,
  },
  accionIconTablon: {
    backgroundColor: theme.colors.primary + '12',
    borderRadius: theme.radius.md,
    padding: 12,
  },
  accionIconNuevaInc: {
    backgroundColor: theme.colors.successLight,
    borderRadius: theme.radius.md,
    padding: 12,
  },
  accionLabel: {
    fontSize: theme.typography.label,
    fontWeight: '600',
    color: theme.colors.text,
  },

  // — Sección título —
  seccionTitulo: {
    fontSize: 18,
    fontWeight: '700',
    color: theme.colors.text,
    marginBottom: theme.spacing.md,
    marginTop: theme.spacing.xs,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: theme.spacing.base,
    marginTop: theme.spacing.xs,
    marginBottom: theme.spacing.md,
  },
  sectionHeaderTextGroup: {
    flex: 1,
  },
  sectionDescription: {
    fontSize: theme.typography.body,
    color: theme.colors.textSecondary,
    lineHeight: 22,
  },
  secondaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.xs,
    backgroundColor: theme.colors.primaryLight,
    borderRadius: theme.radius.full,
    paddingHorizontal: theme.spacing.base,
    paddingVertical: theme.spacing.sm,
    minHeight: 42,
  },
  secondaryButtonPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.97 }],
  },
  secondaryButtonText: {
    fontSize: theme.typography.label,
    fontWeight: '800',
    color: theme.colors.primary,
  },
  modulosSection: {
    marginBottom: theme.spacing.lg,
    gap: theme.spacing.md,
  },
  modulosList: {
    gap: theme.spacing.sm,
  },
  moduloCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.base,
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    padding: theme.spacing.base,
    ...theme.shadows.sm,
  },
  moduloIconBox: {
    width: 44,
    height: 44,
    borderRadius: theme.radius.lg,
    backgroundColor: theme.colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  moduloBody: {
    flex: 1,
    gap: theme.spacing.xs,
  },
  moduloTitulo: {
    fontSize: theme.typography.body,
    fontWeight: '800',
    color: theme.colors.text,
  },
  moduloDescripcion: {
    fontSize: theme.typography.label,
    color: theme.colors.textSecondary,
    lineHeight: 20,
  },
  moduloUpdatingOverlay: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: theme.radius.lg,
    backgroundColor: theme.colors.surface + '66',
  },
  recurringCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.base,
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    padding: theme.spacing.base,
    marginBottom: theme.spacing.md,
    shadowColor: theme.colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  recurringIcon: {
    width: 48,
    height: 48,
    borderRadius: theme.radius.lg,
    backgroundColor: theme.colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  recurringBody: {
    flex: 1,
    gap: theme.spacing.xs,
  },
  recurringTitle: {
    fontSize: theme.typography.body,
    fontWeight: '800',
    color: theme.colors.text,
  },
  recurringMeta: {
    fontSize: theme.typography.label,
    color: theme.colors.textSecondary,
  },
  recurringBadge: {
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.successLight,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: 8,
  },
  recurringBadgeText: {
    color: theme.colors.success,
    fontSize: theme.typography.caption,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0,
  },
  recurringEmptyCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: theme.spacing.base,
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    padding: theme.spacing.base,
    marginBottom: theme.spacing.md,
    shadowColor: theme.colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  recurringEmptyIcon: {
    width: 44,
    height: 44,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  recurringEmptyContent: {
    flex: 1,
    gap: theme.spacing.xs,
  },
  recurringEmptyTitle: {
    fontSize: theme.typography.body,
    fontWeight: '800',
    color: theme.colors.text,
  },
  recurringEmptySubtitle: {
    fontSize: theme.typography.label,
    color: theme.colors.textSecondary,
    lineHeight: 20,
  },

  // — Habitación card —
  habCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    padding: theme.spacing.base,
    marginBottom: theme.spacing.md,
    shadowColor: theme.colors.shadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    gap: theme.spacing.md,
  },
  habCardPressed: { opacity: 0.88 },
  habCardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  habLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
    marginRight: theme.spacing.md,
  },
  habIconBox: {
    backgroundColor: theme.colors.surface2,
    padding: 8,
    borderRadius: 12,
  },
  habNombre: {
    fontSize: theme.typography.body,
    fontWeight: '700',
    color: theme.colors.text,
  },
  habTipo: {
    fontSize: 12,
    color: theme.colors.textTertiary,
    marginTop: 2,
  },
  habInquilinoRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 0,
  },
  habInquilinoNombre: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.text,
  },
  sinInquilino: {
    fontSize: theme.typography.label,
    color: theme.colors.textTertiary,
    fontStyle: 'italic',
    flexShrink: 0,
  },
  habPrecioRow: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.sm,
    backgroundColor: theme.colors.successLight,
    borderRadius: theme.radius.full,
    paddingHorizontal: theme.spacing.base,
    paddingVertical: theme.spacing.sm,
  },
  habPrecioLabel: {
    fontSize: theme.typography.caption,
    fontWeight: '700',
    color: theme.colors.success,
    textTransform: 'uppercase',
    letterSpacing: 0,
  },
  habPrecioValor: {
    fontSize: theme.typography.body,
    fontWeight: '800',
    color: theme.colors.success,
  },

  // — Código de invitación —
  codigoContainer: {
    backgroundColor: theme.colors.surface2,
    borderRadius: theme.radius.md,
    padding: theme.spacing.md,
  },
  codigoLabel: { fontSize: 11, color: theme.colors.textSecondary, marginBottom: theme.spacing.xs },
  codigo: {
    fontSize: 18,
    fontWeight: '700',
    fontFamily: 'Courier New',
    letterSpacing: 0,
    color: theme.colors.text,
  },
  codigoHint: {
    fontSize: 10,
    color: theme.colors.textTertiary,
    marginTop: 2,
  },
  codigoReveladoFila: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  codigoReveladoTextoArea: { flex: 1 },
  codigoOcultoBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: theme.colors.surface2,
    borderRadius: theme.radius.md,
    paddingVertical: 14,
  },
  revelarTexto: { fontSize: 12, fontWeight: '600', color: theme.colors.textSecondary },

  // — Incidencias en card —
  incidenciasHabitacion: {
    borderTopWidth: 1,
    borderTopColor: theme.colors.border,
    paddingTop: theme.spacing.sm,
    gap: 6,
  },
  incidenciaFila: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.sm,
  },
  incidenciaDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    flexShrink: 0,
  },
  incidenciaTitulo: {
    flex: 1,
    fontSize: theme.typography.caption,
    color: theme.colors.textMedium,
  },

  // — Botón añadir habitación —
  botonAnadir: {
    marginTop: theme.spacing.sm,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: theme.colors.overlay,
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: theme.colors.background,
    borderTopLeftRadius: theme.radius.xl,
    borderTopRightRadius: theme.radius.xl,
    paddingHorizontal: theme.spacing.lg,
    paddingTop: theme.spacing.md,
    paddingBottom: theme.spacing.xl,
  },
  modalHandle: {
    width: 44,
    height: 4,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.textMuted,
    alignSelf: 'center',
    marginBottom: theme.spacing.base,
  },
  modalTitulo: {
    fontSize: theme.typography.heading,
    fontWeight: '800',
    color: theme.colors.text,
    marginBottom: theme.spacing.xs,
  },
  modalSubtitulo: {
    fontSize: theme.typography.label,
    color: theme.colors.textSecondary,
    lineHeight: 20,
    marginBottom: theme.spacing.lg,
  },
  infoBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: theme.spacing.sm,
    backgroundColor: theme.colors.primaryLight,
    borderRadius: theme.radius.lg,
    padding: theme.spacing.base,
    marginBottom: theme.spacing.lg,
  },
  infoBannerTexto: {
    flex: 1,
    fontSize: theme.typography.label,
    lineHeight: 20,
    fontWeight: '600',
    color: theme.colors.primary,
  },
  modalAcciones: {
    flexDirection: 'row',
    gap: theme.spacing.sm,
  },
  modalBoton: {
    flex: 1,
  },
});

export const styles = createStyles();
