import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#f5f5f5',
    paddingHorizontal: 32,
  },
  logo: {
    fontSize: 32,
    fontWeight: '800',
    color: '#007AFF',
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitulo: {
    fontSize: 15,
    color: '#6c757d',
    textAlign: 'center',
    marginBottom: 40,
  },
  label: {
    fontSize: 13,
    fontWeight: '600',
    color: '#6c757d',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  input: {
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: '#212529',
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
    elevation: 1,
  },
  inputPasswordFila: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 12,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
    elevation: 1,
  },
  inputPassword: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: '#212529',
  },
  botonVerPass: {
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  botonVerPassTexto: {
    fontSize: 13,
    color: '#9e9e9e',
    fontWeight: '600',
  },
  botonLogin: {
    backgroundColor: '#007AFF',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 8,
  },
  botonLoginDeshabilitado: {
    backgroundColor: '#007AFF',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 8,
    opacity: 0.5,
  },
  botonLoginTexto: {
    color: '#fff',
    fontSize: 17,
    fontWeight: '700',
  },
  enlaceRegistro: {
    marginTop: 24,
    alignItems: 'center',
  },
  enlaceRegistroTexto: {
    fontSize: 14,
    color: '#007AFF',
  },
  separador: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 20,
    marginBottom: 4,
  },
  separadorLinea: {
    flex: 1,
    height: 1,
    backgroundColor: '#dee2e6',
  },
  separadorTexto: {
    fontSize: 13,
    color: '#9e9e9e',
  },
  botonGoogle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingVertical: 14,
    gap: 10,
    marginTop: 12,
    borderWidth: 1.5,
    borderColor: '#dee2e6',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
    elevation: 1,
  },
  botonGoogleTexto: {
    fontSize: 16,
    fontWeight: '600',
    color: '#212529',
  },
});
