import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  scrollContainer: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  container: {
    paddingHorizontal: 32,
    paddingTop: 48,
    paddingBottom: 40,
  },
  titulo: {
    fontSize: 28,
    fontWeight: '800',
    color: '#007AFF',
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitulo: {
    fontSize: 15,
    color: '#6c757d',
    textAlign: 'center',
    marginBottom: 36,
  },
  label: {
    fontSize: 13,
    fontWeight: '600',
    color: '#6c757d',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  input: {
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: '#212529',
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
    elevation: 1,
  },
  inputPasswordFila: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 12,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
    elevation: 1,
  },
  inputPassword: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: '#212529',
  },
  botonVerPass: {
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  botonVerPassTexto: {
    fontSize: 13,
    color: '#9e9e9e',
    fontWeight: '600',
  },
  rolFila: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
  },
  rolPill: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#dee2e6',
    backgroundColor: '#fff',
  },
  rolPillActivo: {
    backgroundColor: '#007AFF',
    borderColor: '#007AFF',
  },
  rolPillTexto: {
    fontSize: 15,
    fontWeight: '600',
    color: '#9e9e9e',
  },
  rolPillTextoActivo: {
    color: '#fff',
  },
  botonRegistrar: {
    backgroundColor: '#007AFF',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 8,
  },
  botonRegistrarDisabled: {
    backgroundColor: '#007AFF',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 8,
    opacity: 0.5,
  },
  botonRegistrarTexto: {
    color: '#fff',
    fontSize: 17,
    fontWeight: '700',
  },
  enlaceLogin: {
    marginTop: 24,
    alignItems: 'center',
  },
  enlaceLoginTexto: {
    fontSize: 14,
    color: '#007AFF',
  },
});
